### ISSUE TITLE
Map voting is still broken.

### ISSUE THREAD

**Issue by thefeddy** [alaswell/PugBot-for-Discord#11]
![screen shot 2018-04-17 at 9 39 25 pm](https://user-images.githubusercontent.com/1827910/38907038-d1612f26-4287-11e8-99ce-f0db245bafb5.png)

**Comment by thefeddy** [comment]
Seems to happen when there are 0-2/3 maps nominated, the game fills and then someone nominates a map.

**Comment by alaswell** [comment]
This has been resolved by the above commit.
